from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime
from app.metrics.base import MetricResult, BaseMetric
from app.models.base import ModelResponse, BaseModel
from app.core.logger import get_logger

# module level logger — captures all pipeline activity
# __name__ resolves to 'app.evaluator.pipeline' for easy log filtering
logger = get_logger(__name__)

@dataclass
class EvaluationResult:
    """
    Represents the complete output of a single evaluation run.
    Contains the original prompt, model response, and all metric scores.
    Stored in the database after each evaluation for historical tracking.
    """
    prompt: str       # the input prompt sent to the model
    model: str        # model identifier e.g. 'anthropic/claude-sonnet-4'
    response: str     # raw text generated by the model
    metrics: dict     # metric name -> MetricResult e.g. {'BLEU': MetricResult(...)}
    # auto-populated with current UTC time when evaluation completes
    timestamp: datetime = field(default_factory=datetime.now)


class EvaluationPipeline:
    """
    Orchestrates the full evaluation workflow.
    
    Accepts a model and a list of metrics at initialization.
    On each evaluate() call:
      1. Sends prompt to the model and captures the response
      2. Runs each metric against the response
      3. Returns a structured EvaluationResult
    
    Designed to be model-agnostic and metric-agnostic —
    swap models or metrics without changing pipeline logic.
    """

    def __init__(self, model: BaseModel, metrics: List[BaseMetric]):
        # model must implement BaseModel.generate()
        self.model = model
        # each metric must implement BaseMetric.compute()
        self.metrics = metrics

    def evaluate(
        self,
        prompt: str,
        reference: Optional[str] = None,   # expected answer for lexical/semantic metrics
        source: Optional[str] = None,       # source document for hallucination detection
        system_prompt: Optional[str] = None, # optional system-level instructions for the model
        max_tokens: int = 1000              # cap on response length
    ) -> EvaluationResult:
        """
        Runs a full evaluation cycle for a single prompt.
        
        Args:
            prompt: the question or input to evaluate
            reference: ground truth answer for BLEU, ROUGE, BERTScore
            source: source document for hallucination detection
            system_prompt: optional behavior instructions for the model
            max_tokens: maximum tokens in the model response
            
        Returns:
            EvaluationResult containing response and all metric scores
            
        Raises:
            Exception: propagates any model or metric failures after logging
        """
        logger.info(f"Starting evaluation | model={self.model.model_id}")

        # step 1 — generate model response
        # wrapped in try/except to log failures before propagating
        try:
            model_response: ModelResponse = self.model.generate(
                prompt=prompt,
                system_prompt=system_prompt,
                max_tokens=max_tokens
            )
        except Exception as e:
            logger.error(f"Model generation failed | error={str(e)}")
            raise

        # step 2 — run each metric against the generated response
        metric_results = {}
        for metric in self.metrics:
            try:
                result: MetricResult = metric.compute(
                    hypothesis=model_response.content,  # what the model said
                    reference=reference,                 # what it should have said
                    source=source                        # what it should be grounded in
                )
                metric_results[metric.name] = result
                logger.info(
                    f"Metric computed | metric={metric.name} | score={result.score}"
                )
            except Exception as e:
                # log which metric failed and why before propagating
                logger.error(
                    f"Metric failed | metric={metric.name} | error={str(e)}"
                )
                raise

        logger.info(
            f"Evaluation complete | metrics={list(metric_results.keys())}"
        )

        # step 3 — package and return structured result
        return EvaluationResult(
            prompt=prompt,
            model=model_response.model,
            response=model_response.content,
            metrics=metric_results
        )